version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/opet/inspira8
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: deploy/permissions.sh
      timeout: 600
      runas: root
    - location: deploy/app_stop.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: deploy/permissions.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: deploy/app_start.sh
      timeout: 600
      runas: root